apiVersion: v2
name: netobserv
description: ElastiFlow NetObserv
type: application
version: 0.3.1
appVersion: 7.0.1

keywords:
  - netflow
  - network
  - flow
  - observability

sources:
  - https://github.com/elastiflow/helm-chart-netobserv
  - https://hub.docker.com/r/elastiflow/flowcollector/
maintainers:
  - name: ElastiFlow Engineering Team
    email: engineering@elastiflow.com
