# Default values for netobserv

opensearch:
  enabled: false

elasticsearch:
  enabled: false

replicaCount: 1

image:
  repository: elastiflow/flow-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:
  - name: EF_LICENSE_ACCEPTED
    value: 'true'
  # EF_FLOW_SERVER_UDP_IP: '0.0.0.0'
  # EF_FLOW_SERVER_UDP_PORT: 9995
  # EF_AWS_VPC_FLOW_LOG_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_APP_ID_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_APP_IPPORT_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_IPADDR_METADATA_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_IPADDR_DNS_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_IPADDR_DNS_NAMESERVER_IP: ''
  # EF_PROCESSOR_ENRICH_IPADDR_DNS_NAMESERVER_TIMEOUT: 3000
  # EF_PROCESSOR_ENRICH_IPADDR_MAXMIND_ASN_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_IPADDR_MAXMIND_GEOIP_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_IPADDR_RISKIQ_THREAT_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_NETIF_METADATA_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_NETIF_FLOW_OPTIONS_ENABLE: 'true'
  # EF_PROCESSOR_ENRICH_NETIF_SNMP_ENABLE: 'false'
  # EF_PROCESSOR_ENRICH_NETIF_SNMP_COMMUNITIES: 'public'
  # EF_OUTPUT_ELASTICSEARCH_ENABLE: 'false'
  # EF_OUTPUT_ELASTICSEARCH_ECS_ENABLE: 'false'
  # EF_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_SHARDS: 1
  # EF_OUTPUT_ELASTICSEARCH_INDEX_TEMPLATE_REPLICAS: 0
  # EF_OUTPUT_ELASTICSEARCH_ADDRESSES: '127.0.0.1:9200'
  # EF_OUTPUT_ELASTICSEARCH_USERNAME: 'elastic'
  # EF_OUTPUT_ELASTICSEARCH_PASSWORD: 'changeme'
  # EF_OUTPUT_ELASTICSEARCH_TLS_ENABLE: 'false'
  # EF_OUTPUT_ELASTICSEARCH_TLS_SKIP_VERIFICATION: 'false'
  # EF_OUTPUT_ELASTICSEARCH_TLS_CA_CERT_FILEPATH: ''
  # EF_OUTPUT_OPENSEARCH_ENABLE: 'false'
  # EF_OUTPUT_OPENSEARCH_ECS_ENABLE: 'false'
  # EF_OUTPUT_OPENSEARCH_INDEX_TEMPLATE_SHARDS: 1
  # EF_OUTPUT_OPENSEARCH_INDEX_TEMPLATE_REPLICAS: 0
  # EF_OUTPUT_OPENSEARCH_ADDRESSES: '127.0.0.1:9200'
  # EF_OUTPUT_OPENSEARCH_USERNAME: 'admin'
  # EF_OUTPUT_OPENSEARCH_PASSWORD: 'admin'
  # EF_OUTPUT_OPENSEARCH_TLS_ENABLE: 'false'
  # EF_OUTPUT_OPENSEARCH_TLS_SKIP_VERIFICATION: 'false'
  # EF_OUTPUT_OPENSEARCH_TLS_CA_CERT_FILEPATH: ''
  # EF_OUTPUT_SPLUNK_HEC_ENABLE: 'false'
  # EF_OUTPUT_SPLUNK_HEC_ADDRESSES: '127.0.0.1:8088'
  # EF_OUTPUT_SPLUNK_HEC_TOKEN: ''
  # EF_OUTPUT_KAFKA_ENABLE: 'false'
  # EF_OUTPUT_KAFKA_BROKERS: ''
  # EF_OUTPUT_KAFKA_SASL_ENABLE: 'false'
  # EF_OUTPUT_CRIBL_ENABLE: 'false'
  # EF_OUTPUT_CRIBL_ADDRESSES: '127.0.0.1:10080'
  # EF_OUTPUT_CRIBL_TOKEN: ''
  # EF_OUTPUT_GENERIC_HTTP_ENABLE: 'false'
  # EF_OUTPUT_GENERIC_HTTP_ECS_ENABLE: 'false'
  # EF_OUTPUT_GENERIC_HTTP_ADDRESSES: ''
  # EF_OUTPUT_RISKIQ_ENABLE: 'false'

# If the EF_PROCESSOR_ENRICH_IPADDR_MAXMIND_ASN_ENABLE or EF_PROCESSOR_ENRICH_IPADDR_MAXMIND_GEOIP_ENABLE
# environment variables are set to true, enable the corresponding service and provide a MaxMind license key:
# https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
maxmind:
  # Enabling asn will look up the autonomous system number and autonomous system
  # organization associated with IPv4 and IPv6 addresses.
  asnEnabled: false
  # Enabling geoip will look up the country, subdivisions (regions), city, and
  # postal code associated with IPv4 and IPv6 addresses.
  geoipEnabled: false
  licenseKey: ""

license:
  # Specifies whether a secret should be created. If you don't have a license, no need to create a license secret.
  createSecret: false
  # Secret name to be used for the license. If empty, the secret name defaults to `netobserv-license`
  # If no secret with a matching name exists, the value will be set from `licenseKey`.instead.
  secretRef: ""
  # Set license key, if not set, value from secret will be used
  licenseKey: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9995

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: false
  httpGet:
    path: /
    port: http
readinessProbe:
  enabled: false
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []
