apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netobserv.fullname" . }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netobserv.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netobserv.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netobserv.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if or .Values.maxmind.asnEnabled .Values.maxmind.geoipEnabled }}
      initContainers:
        {{- if .Values.maxmind.asnEnabled }}
        - name: Download GeoLite2-ASN
          image: curlimages/curl
          command: ["sh", "-c"]
          args:
            - "curl -o /data/GeoLite2-ASN.tar.gz https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key={{ .Values.maxmind.licenseKey }}&suffix=tar.gz && tar -xzvf GeoLite2-ASN.tar.gz && rm GeoLite2-ASN.tar.gz"
          volumeMounts:
            - name: geolite2-data
              mountPath: /data
        {{- end }}
        {{- if .Values.maxmind.geoipEnabled }}
        - name: Download GeoLite2-City
          image: curlimages/curl
          command: ["sh", "-c"]
          args:
            - "curl -o /data/GeoLite2-City.tar.gz https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key={{ .Values.maxmind.licenseKey }}&suffix=tar.gz && tar -xzvf GeoLite2-City.tar.gz && rm GeoLite2-City.tar.gz"
          volumeMounts:
            - name: geolite2-data
              mountPath: /data
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.license.createSecret }}
            - name: EF_FLOW_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: netobserv-license
                  key: license
          {{- end }}
          ports:
            - name: udp
              containerPort: {{ .Values.service.port }}
              protocol: UDP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
            {{- if or .Values.maxmind.asnEnabled .Values.maxmind.geoipEnabled }}
            - name: geolite2-data
              mountPath: /etc/elastiflow/maxmind
            {{- end }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
        {{- if or .Values.maxmind.asnEnabled .Values.maxmind.geoipEnabled }}
        - name: geolite2-data
          emptyDir: {}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
