{{- if .Values.maxmind.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.maxmind.secretRef | default "maxmind-license" }}
type: Opaque
data:
  license: {{ .Values.maxmind.licenseKey | b64enc }}
{{- end }}
