apiVersion: v1
kind: Service
metadata:
  name: {{ include "netobserv.fullname" . }}
  labels:
    {{- include "netobserv.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9995
      protocol: UDP
      name: udp
  selector:
    {{- include "netobserv.selectorLabels" . | nindent 4 }}
